
[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Beam"

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
style = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[general]
live_config_reload = true
working_directory = "None"

[terminal]
