live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
command = "None"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = "Block"
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "Beam"

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.bold]
family = "terminus"
style = "Bold"

[font.bold_italic]
family = "terminus"
style = "Bold Italic"

[font.italic]
family = "terminus"
style = "Italic"

[font.normal]
family = "terminus"
style = "Regular"

[mouse]
hide_when_typing = false

[mouse.hints]
alphabet = "jfkdls;ahgurieowpq"

[[mouse.hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[mouse.hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[mouse.hints.enabled.mouse]
enabled = true
mods = "None"

[[mouse.hints.enabled]]
action = "Copy"
post_processing = false
regex = '([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'

[mouse.hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
gtk_theme_variant = "None"
startup_mode = "Windowed"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"
